### ISSUE TITLE
[question] Pooling with filter 1×1

### ISSUE THREAD

**Issue by akineeic** [google/XNNPACK#472]
It seems all of the pooling operators doesn't support filter size 1×1 with the code like [here](https://github.com/google/XNNPACK/blob/master/src/max-pooling-nhwc.c#L83-L87) since you think 1x1 pooling is meaningless. But recently I'm trying to do inference with tfjs-backend-wasm while the model includes maxpooling with filter 1×1 and stride 2×2. This seems more like a downsampling process and looks meaningful. Do you think the pooling operators should support case like that?

**Comment by Maratyszcza** [comment]
Pooling operations in XNNPACK don't support 1x1 kernel because all cases of 1x1 pooling I've seen are a result of a modelling error. In your case of 1x1 pooling with 2x2 stride, the "max-pooling" operation is, as you correctly noted, de-facto a downsampling operation. Thus, it both faster and more mathematically correct to use an actual downsampling operation instead (e.g. nearest neighbor resize). Even better, you could fuse this downsampling into the operation that produced the input for the 1x1-stride-2 max pooling, but e.g. increasing the stride of the previous convolution by 2x.

**Comment by akineeic** [comment]
Thanks for your attention and the infomation provided.
