### ISSUE TITLE
[PyTorch] XNNPACK `static_assert` not supported on MSVC 2019

### ISSUE THREAD

**Issue by xuhancn** [google/XNNPACK#7534]
My pervious PR to add build option to turn off `libm`, link: https://github.com/google/XNNPACK/pull/7522 

After that, I tried to upgrade `XNNPACK` of `PyTorch`, but I found `static_assert` was not supported on MSVC 2019, error CI link: https://hud.pytorch.org/pr/141754. 

I read the code current `XNNPACK` code use some `static_assert`, such as https://github.com/google/XNNPACK/blob/668a518ebcfd5ae0024ebd9d540868e26ff93171/src/xnnpack/buffer.h#L55 

`static_assert` is not supported well by MSVC 2019, reference: https://learn.microsoft.com/en-us/cpp/build/reference/zc-static-assert?view=msvc-160

So, `static_assert` will bring in some compatibility issue on MSVC 2019. It also limited `XNNPACK` upgrade by `PyTorch`. If we can downgrade `static_assert` to `assert`, and let `XNNPACK` has better compatibility.

CC: @dsharletg

**Comment by gonnet** [comment]
Hi Xu,

I think the problem is that the two-parameter `static_assert(bool, const char *)` is supported, but the single-parameter ``static_assert(bool)` is not. The former is part of the `C++11` standard, whereas the latter was only added to `C++17` ([link](https://en.cppreference.com/w/cpp/language/static_assert)).

Does it work if you add a second parameter `""`, e.g. as is done in `src/xnnpack/buffer.h`?

Cheers, Pedro

**Comment by gonnet** [comment]
Fixed this in #7535.

**Comment by xuhancn** [comment]
Hi @gonnet new error reported from PyTorch CI: https://hud.pytorch.org/pr/141754 
I will setup a local MSVC 2019 environment to do more debug work next week. Thanks.

**Comment by xuhancn** [comment]
Hi @gonnet , I updated `XNNPACK` to 51a0103656eff6fc9bfd39a4597923c4b542c883, it works now.

**Comment by xuhancn** [comment]
Close this issue, due to it was fixed: https://github.com/pytorch/pytorch/pull/141943
